import { collection, doc, setDoc, getDoc } from "firebase/firestore";
import { db } from "../firebase";

type Bus = {
  id: string;
  busNo: string;
  from: string;
  to: string;
  departureTime: string;
  eta: string;
  price: number; // ✅ Added price
};

const buses: Bus[] = [
  {
    id: "BUS_23B",
    busNo: "23B",
    from: "Anna Nagar",
    to: "Periyar Bus Stand",
    departureTime: "12:45 PM",
    eta: "10 mins",
    price: 15,
  },
  {
    id: "BUS_46A",
    busNo: "46A",
    from: "SS Colony",
    to: "Periyar Bus Stand",
    departureTime: "12:50 PM",
    eta: "15 mins",
    price: 18,
  },
  {
    id: "BUS_71C",
    busNo: "71C",
    from: "Thirunagar",
    to: "Periyar Bus Stand",
    departureTime: "1:05 PM",
    eta: "22 mins",
    price: 22,
  },
  {
    id: "BUS_12A",
    busNo: "12A",
    from: "Mattuthavani",
    to: "Arapalayam",
    departureTime: "1:10 PM",
    eta: "18 mins",
    price: 20,
  },
  {
    id: "BUS_18D",
    busNo: "18D",
    from: "Arapalayam",
    to: "Periyar Bus Stand",
    departureTime: "1:15 PM",
    eta: "12 mins",
    price: 16,
  },
  {
    id: "BUS_33C",
    busNo: "33C",
    from: "Goripalayam",
    to: "Mattuthavani",
    departureTime: "1:20 PM",
    eta: "20 mins",
    price: 21,
  },
  {
    id: "BUS_51A",
    busNo: "51A",
    from: "Villapuram",
    to: "Periyar Bus Stand",
    departureTime: "1:25 PM",
    eta: "25 mins",
    price: 25,
  },
  {
    id: "BUS_29B",
    busNo: "29B",
    from: "Simmakkal",
    to: "Arapalayam",
    departureTime: "1:30 PM",
    eta: "14 mins",
    price: 14,
  },
  {
    id: "BUS_40C",
    busNo: "40C",
    from: "Koodal Nagar",
    to: "Mattuthavani",
    departureTime: "1:35 PM",
    eta: "16 mins",
    price: 17,
  },
  {
    id: "BUS_65B",
    busNo: "65B",
    from: "Othakadai",
    to: "Periyar Bus Stand",
    departureTime: "1:40 PM",
    eta: "30 mins",
    price: 28,
  },
  {
    id: "BUS_22A",
    busNo: "22A",
    from: "Anna Nagar",
    to: "Arapalayam",
    departureTime: "1:45 PM",
    eta: "17 mins",
    price: 19,
  },
  {
    id: "BUS_28D",
    busNo: "28D",
    from: "SS Colony",
    to: "Villapuram",
    departureTime: "1:50 PM",
    eta: "19 mins",
    price: 20,
  },
  {
    id: "BUS_35A",
    busNo: "35A",
    from: "Thirunagar",
    to: "Arapalayam",
    departureTime: "1:55 PM",
    eta: "24 mins",
    price: 23,
  },
  {
    id: "BUS_48B",
    busNo: "48B",
    from: "Koodal Nagar",
    to: "Periyar Bus Stand",
    departureTime: "2:00 PM",
    eta: "21 mins",
    price: 22,
  },
  {
    id: "BUS_52C",
    busNo: "52C",
    from: "Mattuthavani",
    to: "Periyar Bus Stand",
    departureTime: "2:05 PM",
    eta: "13 mins",
    price: 15,
  },
  {
    id: "BUS_14B",
    busNo: "14B",
    from: "Villapuram",
    to: "Arapalayam",
    departureTime: "2:10 PM",
    eta: "26 mins",
    price: 26,
  },
  {
    id: "BUS_19A",
    busNo: "19A",
    from: "Simmakkal",
    to: "Periyar Bus Stand",
    departureTime: "2:15 PM",
    eta: "11 mins",
    price: 13,
  },
  {
    id: "BUS_24C",
    busNo: "24C",
    from: "Othakadai",
    to: "Mattuthavani",
    departureTime: "2:20 PM",
    eta: "28 mins",
    price: 27,
  },
  {
    id: "BUS_38D",
    busNo: "38D",
    from: "Goripalayam",
    to: "Arapalayam",
    departureTime: "2:25 PM",
    eta: "15 mins",
    price: 16,
  },
  {
    id: "BUS_44A",
    busNo: "44A",
    from: "Anna Nagar",
    to: "Villapuram",
    departureTime: "2:30 PM",
    eta: "18 mins",
    price: 18,
  },
  {
    id: "BUS_57C",
    busNo: "57C",
    from: "Koodal Nagar",
    to: "Simmakkal",
    departureTime: "2:35 PM",
    eta: "20 mins",
    price: 19,
  },
  {
    id: "BUS_62B",
    busNo: "62B",
    from: "Mattuthavani",
    to: "Villapuram",
    departureTime: "2:40 PM",
    eta: "22 mins",
    price: 21,
  },
  {
    id: "BUS_68A",
    busNo: "68A",
    from: "Othakadai",
    to: "Arapalayam",
    departureTime: "2:45 PM",
    eta: "29 mins",
    price: 28,
  },
  {
    id: "BUS_73D",
    busNo: "73D",
    from: "SS Colony",
    to: "Simmakkal",
    departureTime: "2:50 PM",
    eta: "16 mins",
    price: 17,
  },
  {
    id: "BUS_79B",
    busNo: "79B",
    from: "Villapuram",
    to: "Periyar Bus Stand",
    departureTime: "2:55 PM",
    eta: "23 mins",
    price: 24,
  },
  {
    id: "BUS_81A",
    busNo: "81A",
    from: "Mattuthavani",
    to: "Periyar Bus Stand",
    departureTime: "3:00 PM",
    eta: "12 mins",
    price: 16,
  },
  {
    id: "BUS_82B",
    busNo: "82B",
    from: "Anna Nagar",
    to: "Arapalayam",
    departureTime: "3:05 PM",
    eta: "18 mins",
    price: 19,
  },
  {
    id: "BUS_83C",
    busNo: "83C",
    from: "Thirunagar",
    to: "Periyar Bus Stand",
    departureTime: "3:10 PM",
    eta: "20 mins",
    price: 21,
  },
  {
    id: "BUS_84D",
    busNo: "84D",
    from: "Villapuram",
    to: "Mattuthavani",
    departureTime: "3:15 PM",
    eta: "17 mins",
    price: 18,
  },
  {
    id: "BUS_85A",
    busNo: "85A",
    from: "Simmakkal",
    to: "Periyar Bus Stand",
    departureTime: "3:20 PM",
    eta: "11 mins",
    price: 14,
  },
  {
    id: "BUS_86B",
    busNo: "86B",
    from: "Goripalayam",
    to: "Arapalayam",
    departureTime: "3:25 PM",
    eta: "16 mins",
    price: 17,
  },
  {
    id: "BUS_87C",
    busNo: "87C",
    from: "Othakadai",
    to: "Periyar Bus Stand",
    departureTime: "3:30 PM",
    eta: "28 mins",
    price: 27,
  },
  {
    id: "BUS_88D",
    busNo: "88D",
    from: "Koodal Nagar",
    to: "Mattuthavani",
    departureTime: "3:35 PM",
    eta: "19 mins",
    price: 20,
  },
  {
    id: "BUS_89A",
    busNo: "89A",
    from: "Anna Nagar",
    to: "Villapuram",
    departureTime: "3:40 PM",
    eta: "21 mins",
    price: 22,
  },
  {
    id: "BUS_90B",
    busNo: "90B",
    from: "SS Colony",
    to: "Periyar Bus Stand",
    departureTime: "3:45 PM",
    eta: "14 mins",
    price: 15,
  },

  {
    id: "BUS_91C",
    busNo: "91C",
    from: "Mattuthavani",
    to: "Arapalayam",
    departureTime: "3:50 PM",
    eta: "22 mins",
    price: 23,
  },
  {
    id: "BUS_92D",
    busNo: "92D",
    from: "Villapuram",
    to: "Simmakkal",
    departureTime: "3:55 PM",
    eta: "13 mins",
    price: 14,
  },
  {
    id: "BUS_93A",
    busNo: "93A",
    from: "Thirunagar",
    to: "Mattuthavani",
    departureTime: "4:00 PM",
    eta: "25 mins",
    price: 25,
  },
  {
    id: "BUS_94B",
    busNo: "94B",
    from: "Othakadai",
    to: "Arapalayam",
    departureTime: "4:05 PM",
    eta: "27 mins",
    price: 28,
  },
  {
    id: "BUS_95C",
    busNo: "95C",
    from: "Koodal Nagar",
    to: "Periyar Bus Stand",
    departureTime: "4:10 PM",
    eta: "18 mins",
    price: 19,
  },
  {
    id: "BUS_96D",
    busNo: "96D",
    from: "Anna Nagar",
    to: "Mattuthavani",
    departureTime: "4:15 PM",
    eta: "15 mins",
    price: 16,
  },
  {
    id: "BUS_97A",
    busNo: "97A",
    from: "SS Colony",
    to: "Arapalayam",
    departureTime: "4:20 PM",
    eta: "20 mins",
    price: 21,
  },
  {
    id: "BUS_98B",
    busNo: "98B",
    from: "Villapuram",
    to: "Periyar Bus Stand",
    departureTime: "4:25 PM",
    eta: "23 mins",
    price: 24,
  },
  {
    id: "BUS_99C",
    busNo: "99C",
    from: "Simmakkal",
    to: "Mattuthavani",
    departureTime: "4:30 PM",
    eta: "16 mins",
    price: 17,
  },
  {
    id: "BUS_100D",
    busNo: "100D",
    from: "Goripalayam",
    to: "Periyar Bus Stand",
    departureTime: "4:35 PM",
    eta: "12 mins",
    price: 15,
  },

  {
    id: "BUS_101A",
    busNo: "101A",
    from: "Mattuthavani",
    to: "Villapuram",
    departureTime: "4:40 PM",
    eta: "19 mins",
    price: 20,
  },
  {
    id: "BUS_102B",
    busNo: "102B",
    from: "Othakadai",
    to: "Periyar Bus Stand",
    departureTime: "4:45 PM",
    eta: "30 mins",
    price: 29,
  },
  {
    id: "BUS_103C",
    busNo: "103C",
    from: "Anna Nagar",
    to: "Simmakkal",
    departureTime: "4:50 PM",
    eta: "14 mins",
    price: 15,
  },
  {
    id: "BUS_104D",
    busNo: "104D",
    from: "Thirunagar",
    to: "Arapalayam",
    departureTime: "4:55 PM",
    eta: "24 mins",
    price: 23,
  },
  {
    id: "BUS_105A",
    busNo: "105A",
    from: "Villapuram",
    to: "Mattuthavani",
    departureTime: "5:00 PM",
    eta: "21 mins",
    price: 22,
  },
  {
    id: "BUS_106B",
    busNo: "106B",
    from: "Koodal Nagar",
    to: "Arapalayam",
    departureTime: "5:05 PM",
    eta: "17 mins",
    price: 18,
  },
  {
    id: "BUS_107C",
    busNo: "107C",
    from: "SS Colony",
    to: "Periyar Bus Stand",
    departureTime: "5:10 PM",
    eta: "13 mins",
    price: 14,
  },
  {
    id: "BUS_108D",
    busNo: "108D",
    from: "Goripalayam",
    to: "Mattuthavani",
    departureTime: "5:15 PM",
    eta: "20 mins",
    price: 21,
  },
  {
    id: "BUS_109A",
    busNo: "109A",
    from: "Simmakkal",
    to: "Villapuram",
    departureTime: "5:20 PM",
    eta: "16 mins",
    price: 17,
  },
  {
    id: "BUS_110B",
    busNo: "110B",
    from: "Anna Nagar",
    to: "Periyar Bus Stand",
    departureTime: "5:25 PM",
    eta: "12 mins",
    price: 14,
  },

  {
    id: "BUS_111C",
    busNo: "111C",
    from: "Mattuthavani",
    to: "Simmakkal",
    departureTime: "5:30 PM",
    eta: "18 mins",
    price: 19,
  },
  {
    id: "BUS_112D",
    busNo: "112D",
    from: "Villapuram",
    to: "Arapalayam",
    departureTime: "5:35 PM",
    eta: "23 mins",
    price: 24,
  },
  {
    id: "BUS_113A",
    busNo: "113A",
    from: "Thirunagar",
    to: "Periyar Bus Stand",
    departureTime: "5:40 PM",
    eta: "21 mins",
    price: 22,
  },
  {
    id: "BUS_114B",
    busNo: "114B",
    from: "Othakadai",
    to: "Mattuthavani",
    departureTime: "5:45 PM",
    eta: "27 mins",
    price: 28,
  },
  {
    id: "BUS_115C",
    busNo: "115C",
    from: "SS Colony",
    to: "Villapuram",
    departureTime: "5:50 PM",
    eta: "15 mins",
    price: 16,
  },
  {
    id: "BUS_116D",
    busNo: "116D",
    from: "Koodal Nagar",
    to: "Periyar Bus Stand",
    departureTime: "5:55 PM",
    eta: "20 mins",
    price: 21,
  },
  {
    id: "BUS_117A",
    busNo: "117A",
    from: "Anna Nagar",
    to: "Mattuthavani",
    departureTime: "6:00 PM",
    eta: "17 mins",
    price: 18,
  },
  {
    id: "BUS_118B",
    busNo: "118B",
    from: "Goripalayam",
    to: "Simmakkal",
    departureTime: "6:05 PM",
    eta: "12 mins",
    price: 14,
  },
  {
    id: "BUS_119C",
    busNo: "119C",
    from: "Villapuram",
    to: "Periyar Bus Stand",
    departureTime: "6:10 PM",
    eta: "19 mins",
    price: 20,
  },
  {
    id: "BUS_120D",
    busNo: "120D",
    from: "Mattuthavani",
    to: "Arapalayam",
    departureTime: "6:15 PM",
    eta: "22 mins",
    price: 23,
  },

  {
    id: "BUS_121A",
    busNo: "121A",
    from: "Simmakkal",
    to: "Mattuthavani",
    departureTime: "6:20 PM",
    eta: "16 mins",
    price: 17,
  },
  {
    id: "BUS_122B",
    busNo: "122B",
    from: "Thirunagar",
    to: "Villapuram",
    departureTime: "6:25 PM",
    eta: "24 mins",
    price: 25,
  },
  {
    id: "BUS_123C",
    busNo: "123C",
    from: "Anna Nagar",
    to: "Periyar Bus Stand",
    departureTime: "6:30 PM",
    eta: "13 mins",
    price: 15,
  },
  {
    id: "BUS_124D",
    busNo: "124D",
    from: "Othakadai",
    to: "Simmakkal",
    departureTime: "6:35 PM",
    eta: "26 mins",
    price: 27,
  },
  {
    id: "BUS_125A",
    busNo: "125A",
    from: "Villapuram",
    to: "Mattuthavani",
    departureTime: "6:40 PM",
    eta: "21 mins",
    price: 22,
  },
  {
    id: "BUS_126B",
    busNo: "126B",
    from: "Goripalayam",
    to: "Periyar Bus Stand",
    departureTime: "6:45 PM",
    eta: "14 mins",
    price: 16,
  },
  {
    id: "BUS_127C",
    busNo: "127C",
    from: "SS Colony",
    to: "Mattuthavani",
    departureTime: "6:50 PM",
    eta: "18 mins",
    price: 19,
  },
  {
    id: "BUS_128D",
    busNo: "128D",
    from: "Koodal Nagar",
    to: "Villapuram",
    departureTime: "6:55 PM",
    eta: "20 mins",
    price: 21,
  },
  {
    id: "BUS_129A",
    busNo: "129A",
    from: "Mattuthavani",
    to: "Periyar Bus Stand",
    departureTime: "7:00 PM",
    eta: "12 mins",
    price: 15,
  },
  {
    id: "BUS_130B",
    busNo: "130B",
    from: "Anna Nagar",
    to: "Arapalayam",
    departureTime: "7:05 PM",
    eta: "18 mins",
    price: 19,
  },
];

export const seedBuses = async () => {
  const busesRef = collection(db, "buses");

  for (const bus of buses) {
    const docRef = doc(busesRef, bus.id);
    const existing = await getDoc(docRef);

    if (!existing.exists()) {
      await setDoc(docRef, bus);
      console.log(`✅ Added ${bus.busNo}`);
    } else {
      console.log(`⏭️ Skipped ${bus.busNo} (already exists)`);
    }
  }

  console.log("🚍 Bus seeding completed");
};
